/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User registration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Registration successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klanten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all customers */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of customers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Klant"][];
                            total?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create new customer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateKlantRequest"];
                };
            };
            responses: {
                /** @description Customer created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Klant"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klanten/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Klant"];
                    };
                };
                /** @description Customer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update customer */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateKlantRequest"];
                };
            };
            responses: {
                /** @description Customer updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Klant"];
                    };
                };
            };
        };
        post?: never;
        /** Delete customer */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projecten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all projects */
        get: {
            parameters: {
                query?: {
                    status?: "Planning" | "Actief" | "Afgerond" | "On Hold";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Project"][];
                            total?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create new project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description Project created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facturen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all invoices */
        get: {
            parameters: {
                query?: {
                    status?: "draft" | "openstaand" | "betaald" | "overtijd";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of invoices */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Factuur"][];
                            total?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transacties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all transactions */
        get: {
            parameters: {
                query?: {
                    type?: "inkomst" | "uitgave";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of transactions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Transactie"][];
                            total?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name?: string;
            /** Format: uri */
            avatar_url?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Klant: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            naam: string;
            /** Format: email */
            email: string;
            telefoon?: string;
            adres?: string;
            postcode?: string;
            plaats?: string;
            land?: string;
            bedrijf?: string;
            kvkNummer?: string;
            btwNummer?: string;
            contactpersoon?: string;
            notities?: string;
            /** @enum {string} */
            type: "particulier" | "zakelijk";
            /** @enum {string} */
            status: "actief" | "inactief";
            totaalOmzet?: number;
            /** Format: date */
            laatsteFactuur?: string;
            /** Format: uri */
            avatar?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateKlantRequest: {
            naam: string;
            /** Format: email */
            email: string;
            telefoon?: string;
            adres?: string;
            postcode?: string;
            plaats?: string;
            land?: string;
            bedrijf?: string;
            kvkNummer?: string;
            btwNummer?: string;
            contactpersoon?: string;
            notities?: string;
            /** @enum {string} */
            type: "particulier" | "zakelijk";
        };
        UpdateKlantRequest: {
            naam?: string;
            /** Format: email */
            email?: string;
            telefoon?: string;
            adres?: string;
            postcode?: string;
            plaats?: string;
            land?: string;
            bedrijf?: string;
            kvkNummer?: string;
            btwNummer?: string;
            contactpersoon?: string;
            notities?: string;
            /** @enum {string} */
            type?: "particulier" | "zakelijk";
            /** @enum {string} */
            status?: "actief" | "inactief";
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            name: string;
            /** Format: uuid */
            client_id: string;
            client_name: string;
            location?: string;
            budget: number;
            spent?: number;
            /** @enum {string} */
            status: "Planning" | "Actief" | "Afgerond" | "On Hold";
            progress?: number;
            /** Format: date */
            deadline?: string;
            /** Format: uri */
            image?: string;
            payment_milestones?: components["schemas"]["PaymentMilestone"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateProjectRequest: {
            name: string;
            /** Format: uuid */
            client_id: string;
            client_name: string;
            location?: string;
            budget: number;
            /** Format: date */
            deadline?: string;
            /** Format: uri */
            image?: string;
        };
        PaymentMilestone: {
            /** Format: uuid */
            id: string;
            name: string;
            amount: number;
            /** Format: date */
            due_date: string;
            /** @enum {string} */
            status: "open" | "verzonden" | "betaald";
            percentage: number;
        };
        Factuur: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            number: string;
            /** Format: uuid */
            client_id: string;
            client_name: string;
            amount: number;
            /** Format: date */
            date: string;
            /** Format: date */
            due_date: string;
            /** @enum {string} */
            status: "draft" | "openstaand" | "betaald" | "overtijd";
            items?: components["schemas"]["FactuurRegel"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        FactuurRegel: {
            beschrijving: string;
            aantal: number;
            prijs: number;
            btw: number;
        };
        Transactie: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            titel?: string;
            beschrijving: string;
            bedrag: number;
            /** @enum {string} */
            type: "inkomst" | "uitgave";
            categorie?: string;
            /** Format: date */
            datum: string;
            icon_key?: string;
            rekening?: string;
            referentie?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            session: {
                access_token?: string;
                refresh_token?: string;
                expires_at?: number;
            };
            message?: string;
        };
        Error: {
            error: string;
            message: string;
            code?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
